### ISSUE TITLE
DB storage example?

### ISSUE THREAD

**Issue by ldidry** [juliensobrier/Net-Google-SafeBrowsing4#22]
Hello,

[Net::Google::Safebrowsing3](https://metacpan.org/pod/Net::Google::SafeBrowsing3) had DB storage. Would it be possible to have an example on how to create such DB storage for Net::Google::SafeBrowsing4? At least, clues on how to do that (like "put that object in such table, this one in another table, here's the relations between tables…, or a structure documentation to figure out how we could use DB instead of files). 

Thank you.

**Comment by juliensobrier** [comment]
For GSB v4, using a database as a storage is not ideal like it was with v3. Net::Google::SafeBrowsing4::Storage is the interface to implement for any storage back-end, database or other.  I don't plan on adding an interface for a database.

**Comment by geever** [comment]
I thought the reasons for not adding the DB interface originally were:
a) Not required for initial implementation so the module was released sooner. And
b) Not to add extra dependency that is not needed for everyone.

Due to the second I agree not to add more Storage modules to the base distribution.

However! a DB storage backend is definitely possible, I'm even aware of an existing implementation -  though I cannot share it (unfortunately it's not open-source). 

@ldidry I can try to find some time to put together a basic DB interface during the holidays as a separate distribution. (no guarantees)
